exclude: |
  (?x)^(
      .*\{\{.*\}\}.*|     # Exclude any files with cookiecutter variables
      docs/site/.*|       # Exclude mkdocs compiled files
      \.history/.*|       # Exclude history files
      .*cache.*/.*|       # Exclude cache directories
      .*venv.*/.*|        # Exclude virtual environment directories
  )$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    # --------------------------- ğŸ” Code Quality Tools -------------------------- #
    # Generic checks
    rev: v5.0.0
    hooks:
      - id: check-json
        name: "ğŸ§ª sanity Â· Check JSON files"
      - id: check-yaml
        files: \.yml$
        name: "ğŸ§ª sanity Â· Check YAML files"
      - id: check-toml
        name: "ğŸ§ª sanity Â· Check TOML files"
      - id: check-ast
        name: "ğŸ§ª sanity Â· Check Python syntax (AST)"
  - repo: https://github.com/astral-sh/ruff-pre-commit
    ### Python Tools ###
    rev: v0.14.7
    hooks:
      - id: ruff-format
        name: "ğŸ python Â· Format with Ruff"
      - id: ruff
        name: "ğŸ python Â· Lint and perform safe auto-fixes with Ruff"
        args: [ --fix ]
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.24
    hooks:
      - id: validate-pyproject
        name: "ğŸ python Â· Validate pyproject.toml"
        additional_dependencies: [ "validate-pyproject-schema-store[all]" ]
    ### Notebooks ###
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.1
    hooks:
      - id: nbqa
        entry: nbqa mdformat
        name: "ğŸ““ notebook Â· Format markdown cells"
        args: [ "--nbqa-md" ]
        types: [ jupyter ]
        additional_dependencies:
          - mdformat
          - mdformat-gfm
          - mdformat-ruff
          - mdformat-frontmatter
          - ruff
  - repo: https://github.com/kynan/nbstripout
    # Remove Jupyter Notebook outputs
    rev: 0.8.2
    hooks:
      - id: nbstripout
        name: "ğŸ““ notebook Â· Remove Jupyter Notebook Outputs"
        args: [ '--extra-keys="metadata.kernelspec metadata.celltoolbar cell.metadata.heading_collapsed"' ]
  - repo: https://github.com/pre-commit/mirrors-prettier
    ### Format JS, CSS, HTML and markdown files ###
    rev: v3.1.0
    hooks:
      - id: prettier
        name: "âœ¨ misc-files Â· JS, CSS, HTML, Markdown, JSON, YAML Formatter"
        args: [ "--config", ".prettierrc.yml" ]
        files: "\\.(js|css|html|md|json|json5|jsonc|yaml|yml)$"
  - repo: https://github.com/pre-commit/pre-commit-hooks
    # ---------------------------- ğŸ“ Filesystem Tools --------------------------- #

    rev: v6.0.0
    hooks:
      # Filesystem Checks
      - id: check-executables-have-shebangs
        name: "ğŸ“ filesystem/âš™ï¸ exec Â· Verify shebang presence"
      - id: check-shebang-scripts-are-executable
        name: "ğŸ“ filesystem/âš™ï¸ exec Â· Verify script permissions"
      - id: check-case-conflict
        name: "ğŸ“ filesystem/ğŸ“ names Â· Check case sensitivity"
      - id: check-illegal-windows-names
        name: "ğŸ“ filesystem/ğŸ“ names Â· Validate Windows filenames"
      - id: check-symlinks
        name: "ğŸ“ filesystem/ğŸ”— symlink Â· Check symlink validity"
      - id: destroyed-symlinks
        name: "ğŸ“ filesystem/ğŸ”— symlink Â· Detect broken symlinks"
      - id: check-merge-conflict
        # ------------------------------- ğŸŒ³ Git Tools ------------------------------- #

        name: "ğŸŒ³ git Â· Detect conflict markers"
      - id: forbid-new-submodules
        name: "ğŸŒ³ git Â· Prevent submodule creation"
      - id: no-commit-to-branch
        name: "ğŸŒ³ git Â· Protect main branches"
        args: [ "--branch", "main", "--branch", "master" ]
      - id: check-added-large-files
        name: "ğŸŒ³ git Â· Block large file commits"
        args: [ "--maxkb=512" ]
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.35.0
    hooks:
      - id: check-github-actions
        name: "ğŸ§ª sanity Â· Validate GitHub Actions"
      - id: check-github-workflows
        name: "ğŸ§ª sanity Â· Validate GitHub Workflows"
